
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RecursoHumano_ProyectoFinal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Departamentos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Departamentos()
    {

        this.Empleados = new HashSet<Empleados>();

    }


    public int Id { get; set; }

    public int Codigo_Departamento { get; set; }

    public string Nombre { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Empleados> Empleados { get; set; }

}

}
